x=input("Enter a First number: ")
y=input("Enter a Second number: ")
x=int(x)
y=int(y)
print("Addition : " , x+y )
print("Multiplication : ", x*y)
print("Division : ", int(x/y))
print("Subtraction : ", x-y)
